export interface DetectedObject {
  bbox: [number, number, number, number]; // [x, y, width, height]
  class: string;
  score: number;
  distance?: number;
  position?: "left" | "center" | "right";
}

export interface NavigationInstruction {
  text: string;
  priority: number; // 1: High (obstacle), 2: Medium (info), 3: Low (nav)
}

export type SALanguage = "en-ZA" | "zu-ZA" | "xh-ZA" | "af-ZA" | "st-ZA";

export const LANGUAGES: Record<SALanguage, string> = {
  "en-ZA": "English",
  "zu-ZA": "isiZulu",
  "xh-ZA": "isiXhosa",
  "af-ZA": "Afrikaans",
  "st-ZA": "Sesotho",
};

export const TRANSLATIONS: Record<SALanguage, Record<string, string>> = {
  "en-ZA": {
    obstacle_ahead: "Obstacle ahead, stop or turn.",
    obstacle_left: "Obstacle on your left, move right.",
    obstacle_right: "Obstacle on your right, move left.",
    meters_ahead: "meters ahead",
    starting_nav: "Starting navigation to",
    walk_forward: "Walk forward.",
    person: "person",
    chair: "chair",
    table: "table",
    car: "car",
    bottle: "bottle",
    cup: "cup",
    laptop: "laptop",
    cell_phone: "cell phone",
    backpack: "backpack",
    umbrella: "umbrella",
    handbag: "handbag",
    tie: "tie",
    suitcase: "suitcase",
    frisbee: "frisbee",
    skis: "skis",
    snowboard: "snowboard",
    sports_ball: "sports ball",
    kite: "kite",
    baseball_bat: "baseball bat",
    baseball_glove: "baseball glove",
    skateboard: "skateboard",
    surfboard: "surfboard",
    tennis_racket: "tennis racket",
    wine_glass: "wine glass",
    fork: "fork",
    knife: "knife",
    spoon: "spoon",
    bowl: "bowl",
    banana: "banana",
    apple: "apple",
    sandwich: "sandwich",
    orange: "orange",
    broccoli: "broccoli",
    carrot: "carrot",
    hot_dog: "hot dog",
    pizza: "pizza",
    donut: "donut",
    cake: "cake",
    couch: "couch",
    potted_plant: "potted plant",
    bed: "bed",
    dining_table: "dining table",
    toilet: "toilet",
    tv: "tv",
    mouse: "mouse",
    remote: "remote",
    keyboard: "keyboard",
    microwave: "microwave",
    oven: "oven",
    toaster: "toaster",
    sink: "sink",
    refrigerator: "refrigerator",
    book: "book",
    clock: "clock",
    vase: "vase",
    scissors: "scissors",
    teddy_bear: "teddy bear",
    hair_drier: "hair drier",
    toothbrush: "toothbrush",
    scanning: "Scanning environment...",
  },
  "zu-ZA": {
    obstacle_ahead: "Isithiyo phambili, yima noma uphenduke.",
    obstacle_left: "Isithiyo kwesobunxele, hamba kwesokudla.",
    obstacle_right: "Isithiyo kwesokudla, hamba kwesobunxele.",
    meters_ahead: "amamitha phambili",
    starting_nav: "Ukuqala ukuhamba uya e",
    walk_forward: "Hamba phambili.",
    person: "umuntu",
    chair: "isihlalo",
    table: "itafula",
    car: "imoto",
    bottle: "ibhodlela",
    cup: "inkomishi",
    laptop: "ilaptop",
    cell_phone: "iselula",
    backpack: "ubhakha",
    umbrella: "isambulela",
    handbag: "isikhwama",
    tie: "uthayi",
    suitcase: "isutikesi",
    frisbee: "ifrisbee",
    skis: "izikeyi",
    snowboard: "isnowboard",
    sports_ball: "ibhola",
    kite: "ikayite",
    baseball_bat: "induku ye-baseball",
    baseball_glove: "iglavu ye-baseball",
    skateboard: "isikatebhodi",
    surfboard: "isurfboard",
    tennis_racket: "irakhethi yethenisi",
    wine_glass: "ingilazi yewayini",
    fork: "imfoloko",
    knife: "ummese",
    spoon: "isipuni",
    bowl: "isitya",
    banana: "ubhanana",
    apple: "i-apula",
    sandwich: "isandwich",
    orange: "i-orenji",
    broccoli: "ibroccoli",
    carrot: "isanqante",
    hot_dog: "i-hot dog",
    pizza: "ipizza",
    donut: "idonathi",
    cake: "ikhekhe",
    couch: "usofa",
    potted_plant: "isitshalo esisembizeni",
    bed: "umbhede",
    dining_table: "itafula lokudlela",
    toilet: "ithoyilethe",
    tv: "ithelevishini",
    mouse: "igundane",
    remote: "iremote",
    keyboard: "ikhibhodi",
    microwave: "imayikhrowave",
    oven: "ihhavini",
    toaster: "ithosta",
    sink: "isinki",
    refrigerator: "ifriji",
    book: "incwadi",
    clock: "iwashi",
    vase: "ivazi",
    scissors: "isikelo",
    teddy_bear: "iteddy bear",
    hair_drier: "isomisi sezinwele",
    toothbrush: "isixubho",
    scanning: "Ihlola indawo...",
  },
  "xh-ZA": {
    obstacle_ahead: "Isithintelo phambili, yima okanye ujike.",
    obstacle_left: "Isithintelo kwicala lasekhohlo, hamba ekunene.",
    obstacle_right: "Isithintelo kwicala lasekunene, hamba ekhohlo.",
    meters_ahead: "imitha phambili",
    starting_nav: "Ukuqala ukuhamba uya e",
    walk_forward: "Hamba phambili.",
    person: "umntu",
    chair: "isihlalo",
    table: "itafile",
    car: "imoto",
    bottle: "ibhotile",
    cup: "ikomityi",
    laptop: "ilaptop",
    cell_phone: "iselula",
    backpack: "ubhakha",
    umbrella: "isambulela",
    handbag: "isikhwama",
    tie: "uthayi",
    suitcase: "isutikesi",
    frisbee: "ifrisbee",
    skis: "izikeyi",
    snowboard: "isnowboard",
    sports_ball: "ibhola",
    kite: "ikayite",
    baseball_bat: "induku ye-baseball",
    baseball_glove: "iglavu ye-baseball",
    skateboard: "isikatebhodi",
    surfboard: "isurfboard",
    tennis_racket: "irakhethi yethenisi",
    wine_glass: "ingilazi yewayini",
    fork: "imfoloko",
    knife: "imela",
    spoon: "icephe",
    bowl: "isitya",
    banana: "ibhanana",
    apple: "iapile",
    sandwich: "isandwich",
    orange: "i-orenji",
    broccoli: "ibroccoli",
    carrot: "umnqathe",
    hot_dog: "i-hot dog",
    pizza: "ipizza",
    donut: "idonathi",
    cake: "ikeyiki",
    couch: "isofa",
    potted_plant: "isityalo esisembizeni",
    bed: "umbhede",
    dining_table: "itafile yokutyela",
    toilet: "ithoyilethe",
    tv: "ithelevishini",
    mouse: "imawusi",
    remote: "iremote",
    keyboard: "ikhibhodi",
    microwave: "imayikhrowave",
    oven: "ihovini",
    toaster: "ithosta",
    sink: "isinki",
    refrigerator: "ifriji",
    book: "incwadi",
    clock: "iwashi",
    vase: "ivazi",
    scissors: "isikere",
    teddy_bear: "iteddy bear",
    hair_drier: "isomisi seenwele",
    toothbrush: "isixubho",
    scanning: "Iskena indawo...",
  },
  "af-ZA": {
    obstacle_ahead: "Struikelblok voor, stop of draai.",
    obstacle_left: "Struikelblok aan jou linkerkant, beweeg regs.",
    obstacle_right: "Struikelblok aan jou regterkant, beweeg links.",
    meters_ahead: "meter vorentoe",
    starting_nav: "Begin navigasie na",
    walk_forward: "Stap vorentoe.",
    person: "persoon",
    chair: "stoel",
    table: "tafel",
    car: "motor",
    bottle: "bottel",
    cup: "koppie",
    laptop: "skootrekenaar",
    cell_phone: "selfoon",
    backpack: "rugsak",
    umbrella: "sambreel",
    handbag: "handsak",
    tie: "das",
    suitcase: "tas",
    frisbee: "frisbee",
    skis: "skis",
    snowboard: "snowboard",
    sports_ball: "sportbal",
    kite: "vlieër",
    baseball_bat: "bofbalkolwer",
    baseball_glove: "bofbalhandskoen",
    skateboard: "skaatsplank",
    surfboard: "branderplank",
    tennis_racket: "tennisraket",
    wine_glass: "wynglas",
    fork: "vurk",
    knife: "mes",
    spoon: "lepel",
    bowl: "bak",
    banana: "piesang",
    apple: "appel",
    sandwich: "toebroodjie",
    orange: "lemoen",
    broccoli: "broccoli",
    carrot: "wortel",
    hot_dog: "hot dog",
    pizza: "pizza",
    donut: "donut",
    cake: "koek",
    couch: "bank",
    potted_plant: "potplant",
    bed: "bed",
    dining_table: "eettafel",
    toilet: "toilet",
    tv: "televisie",
    mouse: "muis",
    remote: "afstandbeheer",
    keyboard: "sleutelbord",
    microwave: "mikrogolfoond",
    oven: "oond",
    toaster: "broodrooster",
    sink: "wasbak",
    refrigerator: "yskast",
    book: "boek",
    clock: "horlosie",
    vase: "vaas",
    scissors: "skêr",
    teddy_bear: "teddiebeer",
    hair_drier: "haardroër",
    toothbrush: "tandeborsel",
    scanning: "Skandeer omgewing...",
  },
  "st-ZA": {
    obstacle_ahead: "Tšitiso e kapele, emisa kapa u retehe.",
    obstacle_left: "Tšitiso ka letsohong la hao le letšehali, suthela ka ho le letona.",
    obstacle_right: "Tšitiso ka letsohong la hao le letona, suthela ka ho le letšehali.",
    meters_ahead: "limithara kapele",
    starting_nav: "Ho qala ho tsamaea ho ea",
    walk_forward: "Tsamaea kapele.",
    person: "motho",
    chair: "setulo",
    table: "tafole",
    car: "koloi",
    bottle: "botlolo",
    cup: "komiki",
    laptop: "laptop",
    cell_phone: "founu",
    backpack: "mokotla",
    umbrella: "sekhele",
    handbag: "mokotla oa letsoho",
    tie: "thae",
    suitcase: "sutuk'heise",
    frisbee: "frisbee",
    skis: "skis",
    snowboard: "snowboard",
    sports_ball: "bolo",
    kite: "kite",
    baseball_bat: "baseball bat",
    baseball_glove: "baseball glove",
    skateboard: "skateboard",
    surfboard: "surfboard",
    tennis_racket: "tennis racket",
    wine_glass: "wine glass",
    fork: "foroko",
    knife: "thipa",
    spoon: "khaba",
    bowl: "sekotlolo",
    banana: "panana",
    apple: "apole",
    sandwich: "sandwich",
    orange: "lamunu",
    broccoli: "broccoli",
    carrot: "sehoete",
    hot_dog: "hot dog",
    pizza: "pizza",
    donut: "donut",
    cake: "khekhe",
    couch: "setulo se bonolo",
    potted_plant: "semela",
    bed: "bethe",
    dining_table: "tafole ea ho jela",
    toilet: "ntloana",
    tv: "thelebishene",
    mouse: "mouse",
    remote: "remote",
    keyboard: "keyboard",
    microwave: "microwave",
    oven: "ontong",
    toaster: "toaster",
    sink: "sinki",
    refrigerator: "sehatsetsi",
    book: "buka",
    clock: "oache",
    vase: "vase",
    scissors: "lisekere",
    teddy_bear: "teddy bear",
    hair_drier: "hair drier",
    toothbrush: "borashe ba meno",
    scanning: "Ho hlahloba tikoloho...",
  },
};

export const OBJECT_WIDTHS: Record<string, number> = {
  person: 0.5,
  chair: 0.5,
  table: 1.0,
  car: 1.8,
  bottle: 0.07,
  cup: 0.1,
  laptop: 0.35,
  cell_phone: 0.08,
  backpack: 0.3,
  umbrella: 1.0,
  handbag: 0.25,
  tie: 0.1,
  suitcase: 0.45,
  frisbee: 0.25,
  skis: 0.1,
  snowboard: 0.3,
  sports_ball: 0.2,
  kite: 0.5,
  baseball_bat: 0.05,
  baseball_glove: 0.2,
  skateboard: 0.2,
  surfboard: 0.5,
  tennis_racket: 0.25,
  wine_glass: 0.08,
  fork: 0.02,
  knife: 0.02,
  spoon: 0.02,
  bowl: 0.15,
  banana: 0.05,
  apple: 0.08,
  sandwich: 0.15,
  orange: 0.08,
  broccoli: 0.1,
  carrot: 0.03,
  hot_dog: 0.05,
  pizza: 0.3,
  donut: 0.1,
  cake: 0.2,
  couch: 2.0,
  potted_plant: 0.3,
  bed: 1.5,
  dining_table: 1.2,
  toilet: 0.4,
  tv: 0.8,
  mouse: 0.05,
  remote: 0.05,
  keyboard: 0.4,
  microwave: 0.5,
  oven: 0.6,
  toaster: 0.2,
  sink: 0.5,
  refrigerator: 0.7,
  book: 0.15,
  clock: 0.2,
  vase: 0.15,
  scissors: 0.1,
  teddy_bear: 0.2,
  hair_drier: 0.1,
  toothbrush: 0.02,
};

export const FOCAL_LENGTH = 600; // Configurable constant for distance estimation
